# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlQuadlet < Formula
  desc "create quadlet files from kubernetes manifests"
  homepage "https://github.com/guppy0130/kubectl-quadlet"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/guppy0130/kubectl-quadlet/releases/download/v0.1.0/kubectl-quadlet_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1fa7ff771ff5730fe58ce266a68bad34bc25886239ead31d9bd3a3d69b50ac9"

      def install
        bin.install "kubectl-quadlet"
      end
    end
    on_arm do
      url "https://github.com/guppy0130/kubectl-quadlet/releases/download/v0.1.0/kubectl-quadlet_0.1.0_darwin_arm64.tar.gz"
      sha256 "a9d7ee916debefe26e894824ee8f909419909ce08c6b821050f21843e216ab9c"

      def install
        bin.install "kubectl-quadlet"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guppy0130/kubectl-quadlet/releases/download/v0.1.0/kubectl-quadlet_0.1.0_linux_amd64.tar.gz"
        sha256 "98f5cb5cad158dc28d87637acde815a56688cc3787f7c0dcf296fb3a563bd269"

        def install
          bin.install "kubectl-quadlet"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guppy0130/kubectl-quadlet/releases/download/v0.1.0/kubectl-quadlet_0.1.0_linux_arm64.tar.gz"
        sha256 "b1f8c22bfd955668f571b71aec2b0af6249836186e0c0c7ce8c7f495749e9b0f"

        def install
          bin.install "kubectl-quadlet"
        end
      end
    end
  end
end
